# CS dataset override

data:
  dataset_paths:
    - './data/CS_Xplots_2019_2023_train'
    # - './data/CS2007_Xs_Sept2024_all'
  index_file_names:
    - 'CS_Xplots_2019_23_NEW02OCT24.csv'
    # - 'CS2007_X_with_habs_headrenamed.csv'
  # test_dataset_paths:
  #   - './data/CS_Xplots_2019_2023_test'
  # test_index_file_names:
  #   - 'CS_Xplots_2019_23_NEW02OCT24.csv'
  metadata: False
  batch_size: 16 # batch size used for feature caching. 
  shuffle: True
  num_workers: 0
  data_split:
    valid_split: 0.01
    split_seed: 42
  use_l2_label: False
  preprocessing:
    resize: 439
    resolution: 224        # final crop/resize size for CLIP inputs
    augmentations:
      crop: ratio
      bottom_crop: False
      random_crop: True
      flip: False
      rotation: True
